"""Coulson claim settlements ("debit notes") mirrored and keyed to leads by chassis.

Payload shapes are copied from a live capture of Euler's Claim Settlements List;
identifiers are synthetic so no real dealership record lands in the repo.
"""
import os
import sys
from datetime import datetime, timedelta, timezone

import pytest
import pytest_asyncio

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
os.environ.setdefault("MONGO_URL", "mongodb://localhost:27017")
os.environ.setdefault("DB_NAME", "oem_portal_claims_test")
os.environ.setdefault("JWT_SECRET", "oem-claims-secret")
os.environ["ENVIRONMENT"] = "test"

import motor.motor_asyncio  # noqa: E402
from mongomock_motor import AsyncMongoMockClient  # noqa: E402

motor.motor_asyncio.AsyncIOMotorClient = AsyncMongoMockClient

import httpx  # noqa: E402
import coulson as coulson_client  # noqa: E402
import oem_claims  # noqa: E402
import server  # noqa: E402

CHASSIS = "MD9TESTDL26G900001"
INVOICE = "AF-999-I26279001"
BASE_MOBILE = 9331000000
_seq = {"n": 0}


def next_mobile():
    _seq["n"] += 1
    return str(BASE_MOBILE + _seq["n"])


def list_row(note_id, number, *, status="RM Approval Pending", claimed=5000.0,
             approved=0.0, created="2 Sep 2026 13:34:38", settlement="Sales Invoice"):
    return {
        "id": note_id, "debit_note_number": number, "sap_bill_number": None,
        "_created_at": created, "total_claimed_amount": claimed,
        "total_approved_amount": approved, "status": status,
        "settlement_type": settlement, "showroom_name": "Test Motors Private Limited",
        "city_name": "Jaipur", "current_active_amount": claimed,
        "sales_invoice_number": None, "credit_note_number": None,
        "debit_note_s3_link": f"https://example.invalid/{number}.pdf",
    }


def journey(note_id, number, *, chassis=CHASSIS, invoice=INVOICE, amount=5000.0,
            rm_state="IN_REVIEW", creation_at="2026-09-02 08:04:38"):
    stages = {
        "creation": {"status": "COMPLETED", "date": creation_at,
                     "performed_by": "Test Owner", "remarks": "Claim Form submitted.",
                     "line_item_actions": []},
        "rm_approval": {"status": rm_state, "date": None, "performed_by": None,
                        "remarks": None, "line_item_actions": []},
    }
    for key, _label in oem_claims.CLAIM_STAGES[2:]:
        stages[key] = {"status": "PENDING", "date": None, "performed_by": None,
                       "remarks": None, "line_item_actions": []}
    return {
        "header": {
            "id": note_id, "debit_note_number": number, "status": "RM Approval Pending",
            "settlement_type": "Sales Invoice", "total_claimed_amount": amount,
            "total_approved_amount": 0.0, "current_active_amount": amount,
            "autogenerated": False, "created_at": creation_at,
            "showroom": {"id": "86be8411-0506-4e32-b117-8d94c0d4ec5f",
                         "name": "Test Motors Private Limited",
                         "email": "desk@example.invalid", "phone": "+91 9000000000"},
        },
        "line_items": [{
            "id": "line-1", "claim_type": "Scheme Claim",
            "source_invoice_number": invoice,
            "source_invoice_s3_link": f"https://example.invalid/{invoice}.pdf",
            "model": "Turbo", "variant": "Range Maxx", "status": "In Review",
            "chassis": chassis,
            "description": f"Referral Commission for invoice {invoice}",
            "base_amount": amount, "total_amount": amount,
            "documents": [{"document_id": "d1", "file_url": "https://example.invalid/photo1.jpeg"},
                          {"document_id": "d2", "file_url": "https://example.invalid/photo2.jpeg"}],
            "remarks": None, "rejected_by": None, "history": [],
        }],
        "timeline": stages,
    }


@pytest_asyncio.fixture(autouse=True)
async def isolate_claims():
    """Every test module in this suite shares one mongomock database, so a test that
    counts rows has to start from a known state — and only one lead may ever hold the
    fixture chassis, or the link would land on a leftover from an earlier test.
    """
    await server.db[oem_claims.CLAIMS_COLLECTION].delete_many({})
    await server.db.leads.update_many(
        {"chassisNumber": CHASSIS}, {"$set": {"chassisNumber": "", "invoiceNumber": ""}})
    yield


@pytest_asyncio.fixture
async def client():
    await server.startup()
    transport = httpx.ASGITransport(app=server.app)
    async with httpx.AsyncClient(transport=transport, base_url="http://test") as c:
        r = await c.post("/api/auth/login",
                         json={"email": "owner@euler.com", "password": "euler@123"})
        assert r.status_code == 200, r.text
        c.headers.update({"Authorization": f"Bearer {r.json()['token']}"})
        yield c


@pytest_asyncio.fixture
async def wired(monkeypatch):
    """A stubbed Coulson holding one claim, reachable with a saved session."""
    await server.db["system"].update_one(
        {"_id": "coulson"},
        {"$set": {"username": "tester", "password": "pw", "sessionToken": ""}}, upsert=True)
    monkeypatch.setattr(coulson_client, "login", lambda u, p: "tok")
    calls = {"list": 0, "journey": 0, "status": []}

    def fake_list(token, *, status="", limit=100, max_rows=5000):
        calls["list"] += 1
        calls["status"].append(status)
        return [list_row("n1", "AF-999-CL0001")], 1

    def fake_journey(token, note_id):
        calls["journey"] += 1
        return journey(note_id, "AF-999-CL0001")

    monkeypatch.setattr(coulson_client, "fetch_debit_notes", fake_list)
    monkeypatch.setattr(coulson_client, "fetch_claim_journey", fake_journey)
    monkeypatch.setattr(coulson_client, "fetch_claim_status_counts",
                        lambda t, s="": {"RM Approval Pending": 1})
    return calls


# ---------------------------------------------------------------- dates
def test_list_and_detail_stamps_are_the_same_instant():
    """The list is IST, the journey is UTC, and they are 5h30m apart.

    Reading one with the other's rule shifts every ageing figure by a day.
    """
    from_list = oem_claims.parse_list_datetime("2 Sep 2026 13:34:38")
    from_detail = oem_claims.parse_detail_datetime("2026-09-02 08:04:38")
    assert from_list is not None and from_detail is not None
    assert from_list == from_detail
    assert oem_claims.date_ist(from_list) == "2026-09-02"


def test_detail_stamp_is_not_read_as_local_time():
    naive = datetime(2026, 9, 2, 8, 4, 38, tzinfo=oem_claims.IST)
    assert oem_claims.parse_detail_datetime("2026-09-02 08:04:38") != naive


def test_list_parser_accepts_the_uis_sept_spelling():
    assert oem_claims.parse_list_datetime("2 Sept 2026 13:34:38") == \
        oem_claims.parse_list_datetime("2 Sep 2026 13:34:38")


def test_unparseable_dates_do_not_raise():
    assert oem_claims.parse_list_datetime("") is None
    assert oem_claims.parse_detail_datetime("not a date") is None
    assert oem_claims.days_since(None) == 0


# ---------------------------------------------------------------- ladder
def test_stage_progress_names_the_desk_that_is_holding_it():
    prog = oem_claims.stage_progress(journey("n1", "AF-999-CL0001")["timeline"])
    assert prog["stageKey"] == "rm_approval"
    assert prog["stageLabel"] == "RM Approval"
    assert prog["stageState"] == "IN_REVIEW"
    assert prog["stagesCompleted"] == 1
    assert prog["stagesTotal"] == 7


def test_stage_days_count_from_the_previous_stage_not_from_today():
    """Days parked is the time the CURRENT desk has held it — the chase number."""
    ten_days_ago = (datetime.now(timezone.utc) - timedelta(days=10)).strftime("%Y-%m-%d %H:%M:%S")
    tl = journey("n1", "AF-999-CL0001", creation_at=ten_days_ago)["timeline"]
    assert oem_claims.stage_progress(tl)["stageDays"] == 10


def test_a_finished_ladder_reports_the_last_stage():
    tl = journey("n1", "AF-999-CL0001")["timeline"]
    for key, _ in oem_claims.CLAIM_STAGES:
        tl[key] = {"status": "COMPLETED", "date": "2026-09-02 08:04:38",
                   "performed_by": "Euler", "remarks": "", "line_item_actions": []}
    prog = oem_claims.stage_progress(tl)
    assert prog["stagesCompleted"] == 7
    assert prog["stageKey"] == "bill_posted_in_sap"


def test_terminal_claims_do_not_accrue_ageing():
    for status in ("Settled", "Rejected", "Cancelled"):
        doc = oem_claims.claim_doc_from_row(
            list_row("x", "AF-999-CL0002", status=status, created="1 Aug 2026 10:00:00"))
        assert doc["terminal"] is True
        assert doc["claimAgeingDays"] == 0
    open_doc = oem_claims.claim_doc_from_row(
        list_row("x", "AF-999-CL0003", created="1 Aug 2026 10:00:00"))
    assert open_doc["terminal"] is False
    assert open_doc["claimAgeingDays"] > 0


# ---------------------------------------------------------------- shape
def test_line_item_keeps_the_keys_and_drops_customer_photo_urls():
    """Per-line documents are customer photographs on an open bucket. Count only."""
    line = oem_claims.normalise_line_item(journey("n1", "AF-999-CL0001")["line_items"][0])
    assert line["chassis"] == CHASSIS
    assert line["sourceInvoiceNumber"] == INVOICE
    assert line["claimType"] == "Scheme Claim"
    assert line["totalAmount"] == 5000.0
    assert line["documentCount"] == 2
    assert "documents" not in line
    assert "photo1.jpeg" not in str(line)


def test_chassis_is_normalised_for_matching():
    raw = journey("n1", "AF-999-CL0001")["line_items"][0]
    raw["chassis"] = f"  {CHASSIS.lower()} "
    assert oem_claims.normalise_line_item(raw)["chassis"] == CHASSIS


def test_needs_detail_only_when_something_could_have_changed():
    row = oem_claims.claim_doc_from_row(list_row("n1", "AF-999-CL0001"))
    assert oem_claims.needs_detail({}, row) is True
    fetched = {"detailFetchedAt": "x", "lineItems": [{"chassis": CHASSIS}],
               "detailStatusAtFetch": "RM Approval Pending", "detailAmountAtFetch": 0.0}
    assert oem_claims.needs_detail(fetched, row) is False
    moved = oem_claims.claim_doc_from_row(
        list_row("n1", "AF-999-CL0001", status="Sales Department Approval Pending"))
    assert oem_claims.needs_detail(fetched, moved) is True
    paid = oem_claims.claim_doc_from_row(list_row("n1", "AF-999-CL0001", approved=5000.0))
    assert oem_claims.needs_detail(fetched, paid) is True


# ---------------------------------------------------------------- completeness
def _rows(n):
    return [list_row(f"n{i}", f"AF-999-CL{i:04d}") for i in range(n)]


def test_one_sweep_is_enough_when_it_returns_everything(monkeypatch):
    seen = []

    def fake(token, *, status="", limit=100, max_rows=5000):
        seen.append(status)
        return _rows(3), 3

    monkeypatch.setattr(coulson_client, "fetch_debit_notes", fake)
    monkeypatch.setattr(coulson_client, "fetch_claim_status_counts", lambda t, s="": {"a": 3})
    rows, mode, expected = oem_claims.fetch_all_claims("tok")
    assert len(rows) == 3 and mode == "sweep" and expected == 3
    assert seen == [""]


def test_a_short_sweep_falls_back_to_walking_every_status(monkeypatch):
    """If the API applies a default status filter, a plain sweep mirrors one bucket
    and silently drops the rest. The per-status walk is what stops that."""
    def fake(token, *, status="", limit=100, max_rows=5000):
        if not status:
            return _rows(2), 2
        return [list_row(f"s-{status}", f"AF-999-{status[:4]}")], 1

    monkeypatch.setattr(coulson_client, "fetch_debit_notes", fake)
    monkeypatch.setattr(coulson_client, "fetch_claim_status_counts",
                        lambda t, s="": {s: 1 for s in coulson_client.CLAIM_STATUSES})
    rows, mode, expected = oem_claims.fetch_all_claims("tok")
    assert mode == "per-status"
    assert expected == len(coulson_client.CLAIM_STATUSES)
    assert len(rows) > 2


def test_unreadable_status_counts_do_not_break_the_sync(monkeypatch):
    monkeypatch.setattr(coulson_client, "fetch_debit_notes",
                        lambda t, status="", limit=100, max_rows=5000: (_rows(2), 2))

    def boom(token, showroom_id=""):
        raise coulson_client.CoulsonError("no showroom id")

    monkeypatch.setattr(coulson_client, "fetch_claim_status_counts", boom)
    rows, mode, expected = oem_claims.fetch_all_claims("tok")
    assert len(rows) == 2 and mode == "sweep" and expected == 2


def test_status_counts_total_reads_both_shapes():
    assert oem_claims._status_counts_total({"a": 27, "b": 41}) == 68
    assert oem_claims._status_counts_total([{"status": "a", "count": 27},
                                            {"status": "b", "count": 41}]) == 68
    assert oem_claims._status_counts_total("nonsense") is None


# ---------------------------------------------------------------- linking
async def _delivered_lead(client, *, chassis=CHASSIS, invoice=INVOICE):
    r = await client.post("/api/leads", json={
        "customerName": "Claim Link Test", "mobile": next_mobile(),
        "interestedModel": "Turbo", "variant": "Range Maxx", "executive": "Amit"})
    lead_id = r.json()["leadId"]
    await server.db.leads.update_one(
        {"leadId": lead_id},
        {"$set": {"chassisNumber": chassis, "invoiceNumber": invoice}})
    return lead_id


@pytest.mark.asyncio
async def test_claim_links_to_the_lead_by_chassis(client, wired):
    lead_id = await _delivered_lead(client)
    r = await client.post("/api/integrations/coulson/sync-claims")
    assert r.status_code == 200, r.text
    rows = (await client.get("/api/oem-claims")).json()
    assert len(rows) == 1
    assert rows[0]["leadIds"] == [lead_id]
    assert rows[0]["lineItems"][0]["matchedBy"] == "chassis"
    assert rows[0]["linkedLineCount"] == 1


@pytest.mark.asyncio
async def test_invoice_is_the_fallback_key_when_chassis_is_absent(client, monkeypatch):
    lead_id = await _delivered_lead(client, chassis="MD9OTHER26G900777",
                                    invoice="AF-999-I26279777")
    monkeypatch.setattr(coulson_client, "login", lambda u, p: "tok")
    monkeypatch.setattr(coulson_client, "fetch_debit_notes",
                        lambda t, status="", limit=100, max_rows=5000:
                        ([list_row("inv1", "AF-999-CL7777")], 1))
    monkeypatch.setattr(coulson_client, "fetch_claim_status_counts", lambda t, s="": {"a": 1})
    monkeypatch.setattr(coulson_client, "fetch_claim_journey",
                        lambda t, n: journey(n, "AF-999-CL7777", chassis="",
                                             invoice="AF-999-I26279777"))
    await server.db["system"].update_one(
        {"_id": "coulson"}, {"$set": {"username": "tester", "password": "pw"}}, upsert=True)
    await client.post("/api/integrations/coulson/sync-claims")
    rows = (await client.get("/api/oem-claims", params={"leadId": lead_id})).json()
    assert rows and rows[0]["lineItems"][0]["matchedBy"] == "invoice"


@pytest.mark.asyncio
async def test_chassis_match_with_a_different_invoice_is_flagged_not_hidden(client, monkeypatch):
    lead_id = await _delivered_lead(client, chassis="MD9CONFL26G900888",
                                    invoice="AF-999-I26279888")
    monkeypatch.setattr(coulson_client, "login", lambda u, p: "tok")
    monkeypatch.setattr(coulson_client, "fetch_debit_notes",
                        lambda t, status="", limit=100, max_rows=5000:
                        ([list_row("c1", "AF-999-CL8888")], 1))
    monkeypatch.setattr(coulson_client, "fetch_claim_status_counts", lambda t, s="": {"a": 1})
    monkeypatch.setattr(coulson_client, "fetch_claim_journey",
                        lambda t, n: journey(n, "AF-999-CL8888", chassis="MD9CONFL26G900888",
                                             invoice="AF-999-I26279999"))
    await server.db["system"].update_one(
        {"_id": "coulson"}, {"$set": {"username": "tester", "password": "pw"}}, upsert=True)
    await client.post("/api/integrations/coulson/sync-claims")
    rows = (await client.get("/api/oem-claims", params={"leadId": lead_id})).json()
    assert rows[0]["lineItems"][0]["invoiceMismatch"] is True
    summary = (await client.get("/api/oem-claims/summary")).json()
    assert any("AF-999-CL8888" == c["claimNumber"] for c in summary["invoiceConflicts"])


@pytest.mark.asyncio
async def test_a_claim_for_no_known_lead_is_kept_not_dropped(client, monkeypatch):
    monkeypatch.setattr(coulson_client, "login", lambda u, p: "tok")
    monkeypatch.setattr(coulson_client, "fetch_debit_notes",
                        lambda t, status="", limit=100, max_rows=5000:
                        ([list_row("orphan", "AF-999-CL6000")], 1))
    monkeypatch.setattr(coulson_client, "fetch_claim_status_counts", lambda t, s="": {"a": 1})
    monkeypatch.setattr(coulson_client, "fetch_claim_journey",
                        lambda t, n: journey(n, "AF-999-CL6000", chassis="MD9NOSUCH26G000000",
                                             invoice="AF-999-I26200000"))
    await server.db["system"].update_one(
        {"_id": "coulson"}, {"$set": {"username": "tester", "password": "pw"}}, upsert=True)
    await client.post("/api/integrations/coulson/sync-claims")
    unlinked = (await client.get("/api/oem-claims", params={"unlinked": True})).json()
    assert any(r["claimNumber"] == "AF-999-CL6000" for r in unlinked)


# ---------------------------------------------------------------- sync behaviour
@pytest.mark.asyncio
async def test_second_sync_does_not_refetch_an_unchanged_claim(client, wired):
    await client.post("/api/integrations/coulson/sync-claims")
    first = wired["journey"]
    await client.post("/api/integrations/coulson/sync-claims")
    assert wired["journey"] == first, "unchanged claim was fetched again"


@pytest.mark.asyncio
async def test_sync_reports_when_the_mirror_is_short(client, monkeypatch):
    """A mirror holding 27 of 129 must say so, not look healthy."""
    monkeypatch.setattr(coulson_client, "login", lambda u, p: "tok")
    monkeypatch.setattr(coulson_client, "fetch_debit_notes",
                        lambda t, status="", limit=100, max_rows=5000: (_rows(2), 2))
    monkeypatch.setattr(coulson_client, "fetch_claim_status_counts", lambda t, s="": {"a": 129})
    monkeypatch.setattr(coulson_client, "fetch_claim_journey",
                        lambda t, n: journey(n, "AF-999-CLSHORT"))
    await server.db["system"].update_one(
        {"_id": "coulson"}, {"$set": {"username": "tester", "password": "pw"}}, upsert=True)
    r = await client.post("/api/integrations/coulson/sync-claims")
    body = r.json()
    assert body["claimsIncomplete"] is True
    assert body["claimsExpected"] == 129
    status = (await client.get("/api/integrations/coulson")).json()
    assert status["claimsIncomplete"] is True


@pytest.mark.asyncio
async def test_a_claim_that_leaves_coulson_is_flagged_never_deleted(client, wired, monkeypatch):
    """Claims are a money ledger. Same rule the Scheme Claim Register follows."""
    await client.post("/api/integrations/coulson/sync-claims")
    assert await server.db[oem_claims.CLAIMS_COLLECTION].count_documents({}) == 1
    monkeypatch.setattr(coulson_client, "fetch_debit_notes",
                        lambda t, status="", limit=100, max_rows=5000: ([], 0))
    monkeypatch.setattr(coulson_client, "fetch_claim_status_counts", lambda t, s="": {})
    await client.post("/api/integrations/coulson/sync-claims")
    held = await server.db[oem_claims.CLAIMS_COLLECTION].find_one({"debitNoteId": "n1"})
    assert held is not None, "a claim was deleted from the ledger"
    assert held["missingFromOem"] is True


@pytest.mark.asyncio
async def test_claim_sync_never_writes_to_the_scheme_claim_register(client, wired):
    """The whole reason these live apart: db.claims feeds Owner Commercial,
    Dealer Earnings and the OEM Claim Dashboard."""
    await _delivered_lead(client)
    before = await server.db.claims.count_documents({})
    snapshot = [d async for d in server.db.claims.find({}, {"_id": 0, "claimId": 1,
                                                            "claimStatus": 1,
                                                            "receivedAmount": 1})]
    await client.post("/api/integrations/coulson/sync-claims")
    assert await server.db.claims.count_documents({}) == before
    after = [d async for d in server.db.claims.find({}, {"_id": 0, "claimId": 1,
                                                         "claimStatus": 1,
                                                         "receivedAmount": 1})]
    assert after == snapshot


# ---------------------------------------------------------------- reporting
@pytest.mark.asyncio
async def test_summary_buckets_are_in_ladder_order_with_money(client, wired):
    await client.post("/api/integrations/coulson/sync-claims")
    s = (await client.get("/api/oem-claims/summary")).json()
    assert s["total"] == 1
    assert s["buckets"][0]["status"] == "RM Approval Pending"
    assert s["buckets"][0]["claimed"] == 5000.0
    assert s["totals"]["openClaimed"] == 5000.0
    assert s["stuck"] and s["stuck"][0]["stageLabel"] == "RM Approval"


@pytest.mark.asyncio
async def test_rejected_claims_are_surfaced_for_the_money_desk(client, monkeypatch):
    lead_id = await _delivered_lead(client, chassis="MD9REJ26G900555",
                                    invoice="AF-999-I26279555")
    monkeypatch.setattr(coulson_client, "login", lambda u, p: "tok")
    monkeypatch.setattr(coulson_client, "fetch_debit_notes",
                        lambda t, status="", limit=100, max_rows=5000:
                        ([list_row("rej", "AF-999-CL5555", status="Rejected")], 1))
    monkeypatch.setattr(coulson_client, "fetch_claim_status_counts", lambda t, s="": {"a": 1})
    monkeypatch.setattr(coulson_client, "fetch_claim_journey",
                        lambda t, n: journey(n, "AF-999-CL5555", chassis="MD9REJ26G900555",
                                             invoice="AF-999-I26279555"))
    await server.db["system"].update_one(
        {"_id": "coulson"}, {"$set": {"username": "tester", "password": "pw"}}, upsert=True)
    await client.post("/api/integrations/coulson/sync-claims")
    s = (await client.get("/api/oem-claims/summary")).json()
    assert any(r["claimNumber"] == "AF-999-CL5555" and lead_id in r["leadIds"]
               for r in s["rejected"])


@pytest.mark.asyncio
async def test_lead_endpoint_returns_only_that_leads_lines(client, wired):
    lead_id = await _delivered_lead(client)
    await client.post("/api/integrations/coulson/sync-claims")
    rows = (await client.get(f"/api/leads/{lead_id}/oem-claims")).json()
    assert len(rows) == 1
    assert rows[0]["leadClaimedAmount"] == 5000.0
    assert all(li["leadId"] == lead_id for li in rows[0]["lineItems"])


@pytest.mark.asyncio
async def test_reconciliation_shows_the_three_way_gap(client, wired):
    await _delivered_lead(client)
    await client.post("/api/integrations/coulson/sync-claims")
    r = await client.get("/api/reports/claim-reconciliation")
    assert r.status_code == 200, r.text
    body = r.json()
    assert "entitled" in body["totals"] and "filed" in body["totals"]
    assert body["totals"]["filed"] >= 0


# ---------------------------------------------------------------- access
@pytest.mark.asyncio
async def test_executive_cannot_open_the_oem_claim_register(client):
    transport = httpx.ASGITransport(app=server.app)
    async with httpx.AsyncClient(transport=transport, base_url="http://test") as c:
        r = await c.post("/api/auth/login",
                         json={"email": "executive@euler.com", "password": "euler@123"})
        c.headers.update({"Authorization": f"Bearer {r.json()['token']}"})
        assert (await c.get("/api/oem-claims")).status_code == 403
        assert (await c.get("/api/oem-claims/summary")).status_code == 403
        assert (await c.post("/api/integrations/coulson/sync-claims")).status_code == 403


@pytest.mark.asyncio
async def test_oem_finance_desk_cannot_reach_claims(client):
    """The outside OEM role is allowlisted to one path and must stay there."""
    email, pw = "claims.oemdesk@euler.com", "oemDesk#2026"
    await server.db.users.delete_many({"email": email})
    await client.post("/api/auth/users", json={
        "email": email, "password": pw, "name": "OEM Desk", "role": "oem_finance"})
    transport = httpx.ASGITransport(app=server.app)
    async with httpx.AsyncClient(transport=transport, base_url="http://test") as c:
        r = await c.post("/api/auth/login", json={"email": email, "password": pw})
        c.headers.update({"Authorization": f"Bearer {r.json()['token']}"})
        assert (await c.get("/api/oem-claims")).status_code == 403
